version: '3.9'
services:
  mongo-for-orion-v2:
    image: mongo:${LEPUS_MONGO_DB_VERSION}
    hostname: mongo-db2
    container_name: db-mongo-2
    volumes:
      - mongo-db2:/data
    ports:
      - "${LEPUS_MONGO_DB_PORT}:27017" # localhost:27017
    networks:
      - lepus
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
  lepus:
    image: quay.io/fiware/lepus
    hostname: adapter
    container_name: lepus
    networks:
      - lepus
    expose:
      - "${LEPUS_PORT}"
    ports:
      - "${LEPUS_PORT}:3000"
    environment:
      - DEBUG=adapter:*
      - NGSI_V2_CONTEXT_BROKER=http://orion2:1026/v2
      - CONTEXT_URL=https://fiware.github.io/tutorials.Step-by-Step/tutorials-context.jsonld
      - NOTIFICATION_RELAY_URL=http://adapter:3000/notify

  orion-v2:
    image: quay.io/fiware/orion:${LEPUS_ORION_VERSION}
    hostname: orion2
    container_name: fiware-orion-v2
    depends_on:
      - mongo-for-orion-v2
    networks:
      - lepus
    expose:
      - "${LEPUS_ORION_PORT}"
    ports:
      - "${LEPUS_ORION_PORT}:1026" # localhost:1026
    command: -dbhost mongo-db2 -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion2:1026/version || exit 1
      interval: 5s

networks:
  lepus:
    labels:
      org.fiware: 'tutorial'

volumes:
  mongo-db2: ~