version: '3'

services:
  zookeeper:
    image: zookeeper
    labels:
      org.nec: 'tutorial'
    networks:
      - default
    ports:
      - "2181"
    logging:
      driver: none
  kafka:
    image: bitnami/kafka
    labels:
      org.nec: 'tutorial'
    networks:
      - default
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  postgres:
    image: postgis/postgis
    labels:
      org.nec: 'tutorial'
    networks:
      - default
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
    volumes:
      - scorpio-db:/var/lib/postgresql/data
  scorpio:
    image: scorpiobroker/all-in-one-runner:ubuntu-latest
    labels:
      org.nec: 'tutorial'
    networks:
      - default
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - kafka

networks:
  default:
    labels:
      org.nec: 'tutorial'

volumes:
  scorpio-db: ~