version: '3'

services:
  scorpio-postgres:
    container_name: scorpio-postgres
    image: postgis/postgis
    hostname: postgres
    labels:
      org.nec: 'tutorial'
    networks:
      - scorpio
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
    volumes:
      - scorpio-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ngb"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
  scorpio:
    container_name: scorpio
    image: scorpiobroker/all-in-one-runner:${SCORPIO_VERSION}
    environment:
      DBHOST: postgres
    hostname: scorpio
    labels:
      org.nec: 'tutorial'
    networks:
      - scorpio
    ports:
      - "9090:9090"
    depends_on:
      - scorpio-postgres
    healthcheck:
      test: ["CMD", "true"]
      start_period: 30s

networks:
  scorpio:
    labels:
      org.nec: 'tutorial'

volumes:
  scorpio-db: ~
