services:
  yanb:
    labels:
      org.fiware: 'yanb'
    image: quay.io/seamware/broker:e418bb5
    hostname: yanb
    container_name: fiware-yanb
    networks:
      - yanb
    ports:
      - "${YANB_PORT}:1026"
    healthcheck:
      test: curl --fail -s http://yanb:1026/ngsi-ld/v1/types || exit 1

networks:
  yanb:
    labels:
      org.fiware: 'yanb'
